"use client";
import { useEffect, useState } from "react";
import axios from "axios";

const API = "/api/proxy";

async function getToken(): Promise<string> {
  const cached = sessionStorage.getItem("auth_token");
  if (cached) return cached;
  const r = await axios.post(`${API}/auth/login`, { email: "admin@company.com", password: "Admin@1234" });
  const token: string = r.data.access_token;
  sessionStorage.setItem("auth_token", token);
  return token;
}
async function apiCall<T>(method: string, path: string, body?: any): Promise<T> {
  const token = await getToken();
  try {
    const r = await axios({ method, url: `${API}${path}`, data: body, headers: { Authorization: `Bearer ${token}` } });
    return r.data;
  } catch (e: any) {
    if (e?.response?.status === 401) {
      sessionStorage.removeItem("auth_token");
      const t2 = await getToken();
      const r2 = await axios({ method, url: `${API}${path}`, data: body, headers: { Authorization: `Bearer ${t2}` } });
      return r2.data;
    }
    throw e;
  }
}

interface QueueTicket {
  id: string; ticket_number: string; title: string; description: string;
  priority: string; status: string; category?: string; sub_category?: string;
  urgency_score?: number; ai_summary?: string; ai_suggested_solution?: string;
  routing_confidence?: number; repeat_issue?: boolean; automation_candidate?: boolean;
  similar_ticket_count?: number; routing_reason?: string; assigned_department?: string;
  created_at: string;
}

type NodePhase = "idle" | "running" | "done";
interface AgentNode {
  id: string; icon: string; label: string; model?: string;
  phase: NodePhase; decision?: string; detail?: string;
}

function delay(ms: number) { return new Promise(r => setTimeout(r, ms)); }

const PRIORITY_CHIP: Record<string, string> = {
  critical: "bg-red-900/70 text-red-300 border border-red-700",
  high:     "bg-orange-900/70 text-orange-300 border border-orange-700",
  medium:   "bg-yellow-900/70 text-yellow-300 border border-yellow-700",
  low:      "bg-green-900/70 text-green-300 border border-green-700",
};

const CONFIDENCE_THRESHOLD = 0.90;

function getRouteInfo(t: QueueTicket) {
  const conf = t.routing_confidence ?? 0;
  // Use a small epsilon or round to match backend (2 decimals)
  const roundedConf = Math.round(conf * 100) / 100;
  const isEscalated = (t as any).is_escalated;
  const isResolved = t.status?.toLowerCase() === "resolved";

  if ((t.priority || "").toLowerCase() === "critical" || isEscalated)
    return { key: "escalate", label: "🚨 Escalate — critical priority", color: "red" };
  
  if (roundedConf >= CONFIDENCE_THRESHOLD || (t.similar_ticket_count ?? 0) >= 5) {
    if (t.repeat_issue || (t.similar_ticket_count ?? 0) >= 5)
      return { key: "automated_answer", label: "⚡ Automated Response — pattern detected", color: "purple" };
    return { key: "auto_resolve", label: "✅ Auto-resolve — AI confidence sufficient", color: "green" };
  }
  
  if (isResolved)
    return { key: "auto_resolve", label: "✅ Resolved", color: "green" };

  return { key: "L1", label: `👤 Human Review — confidence ${(conf * 100).toFixed(1)}% < 90%`, color: "yellow" };
}

function buildNodes(t: QueueTicket): AgentNode[] {
  const route = getRouteInfo(t);
  const conf = t.routing_confidence ?? 0;
  const nodesList: AgentNode[] = [
    {
      id: "intake", icon: "📥", label: "Intake", phase: "idle",
      decision: `Ticket ${t.ticket_number} ingested`,
      detail: `${t.description.length} chars · ${t.description.split(" ").length} words`,
    },
    {
      id: "classify", icon: "🧠", label: "Classify", model: "gpt-4.1-nano", phase: "idle",
      decision: `${t.category || "—"}  ·  ${t.sub_category || "—"}`,
      detail: `Priority: ${t.priority?.toUpperCase()}  ·  Urgency: ${t.urgency_score != null ? (t.urgency_score * 100).toFixed(0) + "%" : "—"}`,
    },
    {
      id: "rag", icon: "🔍", label: "RAG Lookup", phase: "idle",
      decision: t.repeat_issue ? `🔁 Repeat issue — ${t.similar_ticket_count} similar tickets found` : "Semantic KB search via Qdrant + BGE",
      detail: t.repeat_issue ? "Pattern detected across past tickets" : (t.ai_summary ? "Relevant articles retrieved" : "No KB match — novel issue"),
    },
    {
      id: "route", icon: "🗺️", label: "Route", model: "gpt-4.1-nano", phase: "idle",
      decision: route.label,
      detail: `Confidence: ${(conf * 100).toFixed(1)}% ${Math.round(conf * 100) / 100 >= CONFIDENCE_THRESHOLD ? "≥" : "<"} 90% threshold`,
    }
  ];

  if (Math.round(conf * 100) / 100 >= CONFIDENCE_THRESHOLD && !((t as any).is_escalated)) {
    nodesList.push({
      id: "resolve", icon: "⚡", label: "Resolution", model: "gpt-4o-mini", phase: "idle",
      decision: t.repeat_issue ? "Automated response from past resolutions" : "Step-by-step resolution plan generated",
      detail: t.ai_suggested_solution ? t.ai_suggested_solution.split("\n")[0].slice(0, 90) : "Solution generated by AI",
    });
  }

  nodesList.push({
    id: "close", icon: "✅", label: "Close", phase: "idle",
    decision: "Awaiting agent confirmation",
    detail: "Click ✅ Mark Resolved below to close this ticket",
  });

  return nodesList;
}

export default function ResolvePage() {
  const [queue,      setQueue]      = useState<QueueTicket[]>([]);
  const [total,      setTotal]      = useState(0);
  const [current,    setCurrent]    = useState<QueueTicket | null>(null);
  const [nodes,      setNodes]      = useState<AgentNode[]>([]);
  const [resolved,   setResolved]   = useState(0);
  const [skipped,    setSkipped]    = useState(0);
  const [phase,      setPhase]      = useState<"idle" | "animating" | "reviewing" | "resolving" | "empty">("idle");
  const [error,      setError]      = useState("");
  const [humanResolution, setHumanResolution] = useState("");

  useEffect(() => { loadQueue(); }, []);

  async function loadQueue() {
    try {
      const data = await apiCall<any>("GET", "/tickets/queue/unprocessed?page_size=100");
      setQueue(data.items ?? []);
      setTotal(data.total ?? 0);
      if ((data.total ?? 0) === 0) setPhase("empty");
    } catch (e: any) { setError(e?.response?.data?.detail || e.message); }
  }

  async function startNext(ticketOverride?: QueueTicket) {
    const ticket = ticketOverride ?? queue[0];
    if (!ticket) { loadQueue(); return; }
    setCurrent(ticket);
    setError("");

    // Build nodes and animate them one by one
    const initial = buildNodes(ticket).map(n => ({ ...n, phase: "idle" as NodePhase }));
    setNodes(initial);
    setPhase("animating");

    for (let i = 0; i < initial.length; i++) {
      // Mark as running
      setNodes(n => n.map((x, j) => j === i ? { ...x, phase: "running" } : x));
      await delay(i === 1 || i === 3 || i === 4 ? 900 : 500); // longer for AI nodes
      // Mark as done
      setNodes(n => n.map((x, j) => j === i ? { ...x, phase: "done" } : x));
      await delay(200);
    }
    
    const conf = ticket.routing_confidence ?? 0;
    const isEscalated = (ticket as any).is_escalated;
    const roundedConf = Math.round(conf * 100) / 100;

    // Auto-resolve if high confidence OR 5+ similar tickets (Automation Opportunity)
    if ((roundedConf >= CONFIDENCE_THRESHOLD || (ticket.similar_ticket_count ?? 0) >= 5) && !isEscalated) {
      setPhase("resolving");
      await delay(1000); // Give user time to see the "Resolution" node
      try {
        await apiCall("POST", `/tickets/${ticket.id}/resolve`, { 
          human_resolution: "System: Auto-resolved via high-confidence batch agent." 
        });
        setResolved(r => r + 1);
        setNodes(n => n.map((x, idx) => idx === (n.length - 1)
          ? { ...x, decision: "✅ Auto-resolved by system", detail: (ticket.similar_ticket_count ?? 0) >= 5 ? "Pattern detected (5+ tickets) — direct resolution applied" : "Confidence ≥ 90% — direct resolution applied" }
          : x));
        await delay(800);
        advanceToNext();
      } catch (e: any) {
        setError("Auto-resolve failed: " + (e?.response?.data?.detail || e.message));
        setPhase("reviewing");
      }
    } else {
      setPhase("reviewing");
    }
  }

  async function resolveTicket() {
    if (!current) return;
    setPhase("resolving");
    try {
      await apiCall("POST", `/tickets/${current.id}/resolve`, { human_resolution: humanResolution });
      setResolved(r => r + 1);
      // Mark close node as confirmed
      setNodes(n => n.map((x, i) => i === 5
        ? { ...x, decision: "✅ Resolved by agent", detail: "Ticket closed and logged" }
        : x));
      await delay(600);
      setHumanResolution("");
      advanceToNext();
    } catch (e: any) {
      setError(e?.response?.data?.detail || e.message);
      setPhase("reviewing");
    }
  }

  function skipTicket() {
    setSkipped(s => s + 1);
    advanceToNext();
  }

  function advanceToNext() {
    setQueue(prev => {
      const nextQueue = prev.slice(1);
      if (nextQueue.length > 0) {
        // Schedule next ticket after state update
        setTimeout(() => startNext(nextQueue[0]), 0);
      } else {
        // Empty queue
        setTimeout(() => {
          setCurrent(null);
          setPhase("idle");
          setHumanResolution("");
          loadQueue();
        }, 0);
      }
      return nextQueue;
    });
  }

  const remaining = Math.max(0, total - resolved - skipped);

  return (
    <div className="min-h-screen bg-gray-950 text-white">

      {/* ── Top Bar ───────────────────────────────────────────────────── */}
      <div className="border-b border-gray-800 bg-gray-900/70 backdrop-blur-md px-6 py-3 sticky top-0 z-20">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div>
            <h1 className="text-lg font-bold flex items-center gap-2">
              🤖 Agentic Batch Resolver
              <span className="text-xs font-normal text-gray-500 ml-1 border border-gray-700 rounded-full px-2 py-0.5">
                gpt-4.1-nano · gpt-4o-mini · BGE Embeddings · Qdrant RAG
              </span>
            </h1>
          </div>
          <div className="flex items-center gap-5 text-sm">
            <div className="text-center"><div className="text-xs text-gray-500">✅ Resolved</div><div className="text-xl font-bold text-green-400">{resolved}</div></div>
            <div className="text-center"><div className="text-xs text-gray-500">⏭ Skipped</div><div className="text-xl font-bold text-gray-500">{skipped}</div></div>
            <div className="text-center"><div className="text-xs text-gray-500">📋 Remaining</div><div className="text-xl font-bold text-yellow-400">{remaining}</div></div>
            <a href="/" className="text-indigo-400 hover:text-indigo-300 text-sm ml-2">← Dashboard</a>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 py-6">
        {error && (
          <div className="mb-4 bg-red-950/50 border border-red-700 rounded-xl px-4 py-3 text-red-300 text-sm">⚠️ {error}</div>
        )}

        {/* ── Idle / Empty ─────────────────────────────────────────────── */}
        {(phase === "idle" || phase === "empty") && (
          <div className="flex flex-col items-center justify-center py-20 gap-5">
            {phase === "empty" ? (
              <>
                <div className="text-6xl">🎉</div>
                <h2 className="text-2xl font-bold text-green-400">All caught up!</h2>
                <p className="text-gray-400">No more tickets awaiting review.</p>
                <button onClick={loadQueue} className="bg-gray-700 hover:bg-gray-600 px-6 py-3 rounded-xl transition">Refresh Queue</button>
              </>
            ) : (
              <>
                <div className="text-5xl">🤖</div>
                <h2 className="text-2xl font-bold">{remaining} tickets awaiting agent review</h2>
                <p className="text-gray-400 text-center max-w-lg">
                  Each ticket has been processed by the <strong>6-node AI pipeline</strong>.<br/>
                  Review the agentic decisions and solution, then confirm or skip.
                </p>
                <div className="flex gap-3 text-xs text-gray-600 border border-gray-800 rounded-xl px-5 py-3 bg-gray-900/40">
                  <span>📥 Intake</span><span>→</span>
                  <span className="text-indigo-400">🧠 gpt-4.1-nano Classify</span><span>→</span>
                  <span>🔍 RAG Qdrant</span><span>→</span>
                  <span className="text-indigo-400">🗺️ gpt-4.1-nano Route</span><span>→</span>
                  <span className="text-purple-400">⚡ gpt-4o-mini Resolve</span><span>→</span>
                  <span>✅ Close</span>
                </div>
                <button onClick={() => startNext()}
                  className="mt-2 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 px-10 py-4 rounded-xl font-semibold text-lg transition shadow-lg shadow-indigo-900/30 active:scale-[0.98]">
                  🚀 Start Reviewing
                </button>
              </>
            )}
          </div>
        )}

        {/* ── Main Review Layout ───────────────────────────────────────── */}
        {current && (phase === "animating" || phase === "reviewing" || phase === "resolving") && (
          <div className="grid grid-cols-1 xl:grid-cols-5 gap-5">

            {/* ── Col 1-2: Agentic Pipeline ──────────────────────────── */}
            <div className="xl:col-span-2 space-y-3">
              {/* Ticket chip */}
              <div className="flex items-center gap-3 bg-gray-800/60 border border-gray-700 rounded-xl px-4 py-3">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-indigo-400 text-sm font-bold">{current.ticket_number}</span>
                    <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${PRIORITY_CHIP[(current.priority || "medium").toLowerCase()] || PRIORITY_CHIP.medium}`}>
                      {(current.priority || "MEDIUM").toUpperCase()}
                    </span>
                  </div>
                  <div className="text-white font-semibold mt-0.5 truncate">{current.title}</div>
                </div>
                <div className="text-xs text-gray-500">{new Date(current.created_at).toLocaleDateString()}</div>
              </div>

              {/* Pipeline nodes */}
              <div className="bg-gray-900/50 border border-gray-700/60 rounded-2xl p-4 space-y-1.5">
                <div className="text-xs text-gray-500 uppercase tracking-widest mb-3 flex items-center gap-2">
                  <span>Agentic Pipeline</span>
                  <span className="border border-gray-700 rounded px-1.5 py-0.5 text-gray-600">6 nodes</span>
                </div>
                {nodes.map((node, i) => (
                  <div key={node.id}
                    className={`rounded-xl border px-4 py-3 transition-all duration-500 ${
                      node.phase === "done"    ? "border-green-700/50 bg-green-950/20" :
                      node.phase === "running" ? "border-yellow-500/60 bg-yellow-950/20" :
                      "border-gray-800 bg-gray-900/30"
                    }`}>
                    <div className="flex items-start gap-3">
                      {/* Status dot */}
                      <span className={`mt-0.5 flex-shrink-0 w-5 h-5 rounded-full flex items-center justify-center text-xs font-bold transition-all ${
                        node.phase === "done"    ? "bg-green-700 text-white" :
                        node.phase === "running" ? "bg-yellow-600 text-black animate-pulse" :
                        "bg-gray-800 text-gray-600"
                      }`}>
                        {node.phase === "done" ? "✓" : node.phase === "running" ? "⟳" : String(i + 1)}
                      </span>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap">
                          <span>{node.icon}</span>
                          <span className={`font-semibold text-sm ${node.phase === "idle" ? "text-gray-500" : "text-white"}`}>
                            {node.label}
                          </span>
                          {node.model && (
                            <span className={`text-xs px-1.5 py-0.5 rounded border ${
                              node.model === "gpt-4o-mini"
                                ? "border-purple-700/60 text-purple-400 bg-purple-950/30"
                                : "border-indigo-700/60 text-indigo-400 bg-indigo-950/30"
                            }`}>{node.model}</span>
                          )}
                          {!node.model && node.id === "rag" && (
                            <span className="text-xs px-1.5 py-0.5 rounded border border-cyan-700/60 text-cyan-400 bg-cyan-950/30">BGE + Qdrant</span>
                          )}
                        </div>
                        {node.phase !== "idle" && node.decision && (
                          <div className={`text-sm mt-1 transition-all ${
                            node.phase === "running" ? "text-yellow-300" : "text-gray-200"
                          }`}>{node.decision}</div>
                        )}
                        {node.phase === "done" && node.detail && (
                          <div className="text-xs text-gray-500 mt-0.5 truncate">{node.detail}</div>
                        )}
                        {node.phase === "running" && (
                          <div className="flex gap-1 mt-2">
                            {[0,1,2].map(d => (
                              <div key={d} className="w-1.5 h-1.5 rounded-full bg-yellow-500 animate-bounce"
                                style={{ animationDelay: `${d * 150}ms` }} />
                            ))}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Action buttons — shown only after animation */}
              {phase === "reviewing" && (
                <div className="space-y-4">
                  {(Math.round((current.routing_confidence ?? 0) * 100) / 100 < CONFIDENCE_THRESHOLD || (current as any).is_escalated) && (
                    <div className="bg-gray-800/60 border border-gray-700 rounded-xl p-4">
                      <label className="block text-sm font-semibold text-gray-300 mb-2">
                        ✍️ Provide Human Resolution
                      </label>
                      <textarea
                        value={humanResolution}
                        onChange={(e) => setHumanResolution(e.target.value)}
                        placeholder="Enter the steps taken to resolve this escalated ticket..."
                        className="w-full bg-gray-900 border border-gray-700 rounded-lg p-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition"
                        rows={4}
                      />
                    </div>
                  )}
                  <div className="space-y-2">
                  <button onClick={resolveTicket}
                    className="w-full py-3.5 rounded-xl font-semibold bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-500 hover:to-emerald-500 transition shadow-lg shadow-green-900/30 flex items-center justify-center gap-2 text-base active:scale-[0.98]">
                    ✅ Mark as Resolved
                  </button>
                  <button onClick={skipTicket}
                    className="w-full py-3 rounded-xl font-semibold bg-gray-800 hover:bg-gray-700 transition text-gray-300">
                    ⏭ Skip — review later
                  </button>
                  </div>
                </div>
              )}
              {phase === "resolving" && (
                <div className="w-full py-3.5 rounded-xl font-semibold bg-green-800/50 text-green-300 text-center animate-pulse">
                  ⟳ Resolving...
                </div>
              )}
            </div>

            {/* ── Col 3-5: AI Output ────────────────────────────────────── */}
            <div className="xl:col-span-3 space-y-4">
              {/* Original ticket */}
              <div className="bg-gray-800/60 border border-gray-700 rounded-2xl p-5">
                <div className="text-xs text-gray-500 uppercase tracking-wider mb-2">📋 Original Ticket</div>
                <p className="text-gray-300 text-sm leading-relaxed">{current.description}</p>
              </div>

              {/* AI Classification (visible once classify node is done) */}
              {(nodes[1]?.phase === "done") && (
                <div className="bg-indigo-950/30 border border-indigo-700/40 rounded-2xl p-5 transition-all duration-700">
                  <div className="flex items-center gap-2 mb-3">
                    <span className="text-lg">🧠</span>
                    <span className="text-indigo-400 font-semibold text-sm">AI Classification</span>
                    <span className="ml-auto text-xs border border-indigo-800 text-indigo-500 rounded px-2 py-0.5">gpt-4.1-nano</span>
                  </div>
                  <div className="grid grid-cols-3 gap-3 text-sm mb-3">
                    {[
                      ["Category",    current.category || "—"],
                      ["Sub-category",current.sub_category || "—"],
                      ["Priority",    (current.priority || "—").toUpperCase()],
                    ].map(([k, v]) => (
                      <div key={k} className="bg-gray-900/60 rounded-lg p-2.5">
                        <div className="text-gray-500 text-xs">{k}</div>
                        <div className="text-white font-medium mt-0.5 truncate">{v}</div>
                      </div>
                    ))}
                  </div>
                  {current.urgency_score != null && (
                    <div>
                      <div className="flex justify-between text-xs text-gray-500 mb-1">
                        <span>Urgency Score</span>
                        <span>{(current.urgency_score * 100).toFixed(0)}%</span>
                      </div>
                      <div className="w-full bg-gray-800 rounded-full h-2">
                        <div className={`h-2 rounded-full transition-all duration-700 ${
                          current.urgency_score > 0.8 ? "bg-orange-500" : current.urgency_score > 0.5 ? "bg-indigo-500" : "bg-green-500"
                        }`} style={{ width: `${current.urgency_score * 100}%` }} />
                      </div>
                    </div>
                  )}
                  {current.ai_summary && (
                    <div className="mt-3 bg-gray-900/50 rounded-lg p-3">
                      <div className="text-gray-500 text-xs mb-1">AI Summary</div>
                      <div className="text-gray-200 text-sm">{current.ai_summary}</div>
                    </div>
                  )}
                </div>
              )}

              {/* Confidence + Routing Decision */}
              {(nodes[3]?.phase === "done") && (() => {
                const conf = current.routing_confidence ?? 0;
                const roundedConf = Math.round(conf * 100) / 100;
                const pct  = Math.round(conf * 100);
                const route = getRouteInfo(current);
                const barColor = roundedConf >= CONFIDENCE_THRESHOLD ? "bg-green-500" : roundedConf >= 0.7 ? "bg-yellow-500" : "bg-red-500";
                const cardColor = route.color === "green" ? "bg-green-950/30 border-green-700/40"
                  : route.color === "purple" ? "bg-purple-950/30 border-purple-700/40"
                  : route.color === "red"    ? "bg-red-950/30 border-red-700/40"
                  : "bg-yellow-950/30 border-yellow-700/40";
                return (
                  <div className={`border rounded-2xl p-5 transition-all duration-700 ${cardColor}`}>
                    <div className="flex items-center gap-2 mb-3">
                      <span className="text-lg">🗺️</span>
                      <span className="text-yellow-400 font-semibold text-sm">Routing Decision</span>
                      <span className="ml-auto text-xs border border-yellow-900 text-yellow-600 rounded px-2 py-0.5">gpt-4.1-nano</span>
                    </div>
                    {/* Confidence gauge */}
                    <div className="mb-3">
                      <div className="flex justify-between items-center text-xs mb-1">
                        <span className="text-gray-400 font-medium">AI Confidence Score</span>
                        <span className={`font-bold text-base ${conf >= CONFIDENCE_THRESHOLD ? "text-green-400" : "text-yellow-400"}`}>{pct}%</span>
                      </div>
                      <div className="w-full bg-gray-800 rounded-full h-3 relative">
                        <div className={`h-3 rounded-full transition-all duration-700 ${barColor}`} style={{ width: `${pct}%` }} />
                        {/* 90% threshold marker */}
                        <div className="absolute top-0 h-3 w-0.5 bg-white/60" style={{ left: "90%" }} />
                        <span className="absolute -top-4 text-[10px] text-white/40" style={{ left: "88%" }}>90%</span>
                      </div>
                      <div className="flex justify-between text-[10px] text-gray-600 mt-1">
                        <span>0% (uncertain)</span>
                        <span className={roundedConf >= CONFIDENCE_THRESHOLD ? "text-green-500 font-semibold" : "text-yellow-500 font-semibold"}>
                          {roundedConf >= CONFIDENCE_THRESHOLD ? "✓ Above threshold → AI handles it" : "⚠ Below 90% → Human review required"}
                        </span>
                        <span>100% (certain)</span>
                      </div>
                    </div>
                    <div className="text-white font-semibold text-sm">{route.label}</div>
                    {current.routing_reason && (
                      <div className="text-gray-400 text-xs mt-1 leading-relaxed">{current.routing_reason}</div>
                    )}
                    {current.assigned_department && (
                      <div className="mt-2 text-xs text-indigo-400">🏢 {current.assigned_department}</div>
                    )}
                  </div>
                );
              })()}

              {/* Automation Suggestion */}
              {(nodes[3]?.phase === "done") && current.automation_candidate && (
                <div className="bg-amber-950/30 border border-amber-600/50 rounded-2xl p-4 transition-all duration-700">
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-lg">🤖</span>
                    <span className="text-amber-400 font-semibold text-sm">Automation Opportunity Detected</span>
                  </div>
                  <p className="text-amber-200 text-xs leading-relaxed">
                    This issue has appeared <strong>{current.similar_ticket_count}+ times</strong>. Consider building an automated resolution workflow or self-service tool for this pattern.
                  </p>
                  <div className="mt-2 flex gap-2 flex-wrap">
                    {["Create runbook", "Add self-service fix", "Build automation script"].map(a => (
                      <span key={a} className="text-xs px-2 py-1 bg-amber-900/40 border border-amber-700/50 rounded-full text-amber-300">{a}</span>
                    ))}
                  </div>
                </div>
              )}

              {/* AI Solution (visible once resolve node is done) */}
              {(nodes.find(n => n.id === "resolve")?.phase === "done") && current.ai_suggested_solution && (
                <div className="bg-purple-950/20 border border-purple-700/40 rounded-2xl p-5 transition-all duration-700">
                  <div className="flex items-center gap-2 mb-3">
                    <span className="text-lg">{current.repeat_issue ? "⚡" : "⚡"}</span>
                    <span className="text-purple-400 font-semibold text-sm">
                      {current.repeat_issue ? "⚡ Automated Response (from past resolutions)" : "AI Resolution Plan"}
                    </span>
                    <span className="ml-auto text-xs border border-purple-800 text-purple-400 rounded px-2 py-0.5">gpt-4o-mini</span>
                  </div>
                  <pre className="text-gray-200 text-sm whitespace-pre-wrap leading-relaxed font-sans">
                    {current.ai_suggested_solution}
                  </pre>
                </div>
              )}

              {/* Queue preview */}
              {queue.length > 0 && (
                <div className="bg-gray-900/40 border border-gray-800 rounded-xl p-4">
                  <div className="text-xs text-gray-600 uppercase tracking-wide mb-2">Up next in queue</div>
                  <div className="space-y-1.5">
                    {queue.slice(0, 4).map((t, i) => (
                      <div key={t.id} className="flex items-center gap-2 text-sm">
                        <span className="text-gray-700 text-xs w-4">{i + 1}</span>
                        <span className="font-mono text-indigo-500 text-xs">{t.ticket_number}</span>
                        <span className="text-gray-400 truncate flex-1">{t.title}</span>
                        <span className={`px-1.5 py-0.5 rounded text-xs flex-shrink-0 ${PRIORITY_CHIP[t.priority?.toLowerCase()] || PRIORITY_CHIP.medium}`}>
                          {t.priority?.toUpperCase()}
                        </span>
                      </div>
                    ))}
                    {queue.length > 4 && <div className="text-xs text-gray-700 text-center">+{queue.length - 4} more</div>}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
