"use client";
import { useState } from "react";
import axios from "axios";
const API = "/api/proxy";
const NODES = ["📥 Intake","🧠 Classify","🔍 RAG Lookup","🗺️ Route","⚡ Resolve","✅ Close"];

// Shared token cache — avoids re-login on every demo run
async function getToken(): Promise<string> {
  const cached = sessionStorage.getItem("auth_token");
  if (cached) return cached;
  const r = await axios.post(`${API}/auth/login`, {
    email: "admin@company.com",
    password: "Admin@1234",
  });
  const token: string = r.data.access_token;
  sessionStorage.setItem("auth_token", token);
  return token;
}
interface Step { node: string; status: "idle"|"running"|"done"|"error"; data?: any; ms?: number; }
export default function DemoPage() {
  const [title, setTitle]   = useState("VPN not working after Windows update");
  const [desc,  setDesc]    = useState("Cannot connect to corporate VPN since the last Windows update. Error code 800. Already tried restarting and reinstalling the VPN client but still failing.");
  const [steps, setSteps]   = useState<Step[]>(NODES.map(n => ({ node: n, status: "idle" })));
  const [result, setResult] = useState<any>(null);
  const [running, setRunning] = useState(false);
  async function runDemo() {
    setRunning(true);
    setResult(null);
    const fresh = NODES.map(n => ({ node: n, status: "idle" as const }));
    setSteps(fresh);
    let token: string;
    try {
      token = await getToken();
    } catch (e: any) {
      sessionStorage.removeItem("auth_token");
      token = await getToken();
    }
    const h = { Authorization: `Bearer ${token}` };
    // Step 0: Intake
    setSteps(s => s.map((x,i) => i===0 ? {...x, status:"running"} : x));
    const t0 = Date.now();
    const ticket = (await axios.post(`${API}/tickets`,
      { title, description: desc, priority: "high" }, { headers: h })).data;
    setSteps(s => s.map((x,i) => i===0 ? {...x, status:"done", data: ticket.ticket_number, ms: Date.now()-t0} : x));
    await delay(600);
    // Step 1: Classify (poll until category set)
    setSteps(s => s.map((x,i) => i===1 ? {...x, status:"running"} : x));
    const t1 = Date.now();
    let classified: any = ticket;
    for (let attempt = 0; attempt < 30; attempt++) {
      await delay(3000);
      classified = (await axios.get(`${API}/tickets/${ticket.id}`, { headers: h })).data;
      if (classified.category) break;
    }
    setSteps(s => s.map((x,i) => i===1 ? {...x, status:"done",
      data: `${classified.category} / ${classified.priority}`, ms: Date.now()-t1} : x));
    await delay(400);
    // Step 2: RAG lookup (simulated from ai_summary)
    setSteps(s => s.map((x,i) => i===2 ? {...x, status:"running"} : x));
    await delay(800);
    setSteps(s => s.map((x,i) => i===2 ? {...x, status:"done",
      data: classified.rag_kb_articles?.length ? `${classified.rag_kb_articles.length} KB articles found` : "0 KB articles (new issue)"} : x));
    await delay(400);
    // Step 3: Route
    setSteps(s => s.map((x,i) => i===3 ? {...x, status:"running"} : x));
    await delay(600);
    const routeMap: Record<string,string> = {
      "Network":"L2 Network","Infrastructure":"L3 Software",
      "Application":"L3 Software","Security":"L3 Security",
      "Access Management":"L1 Support","Database":"L3 Software",
    };
    const group = routeMap[classified.category] || "L1 Support";
    setSteps(s => s.map((x,i) => i===3 ? {...x, status:"done", data:`Assigned → ${group}`} : x));
    await delay(400);
    // Step 4: Resolve
    setSteps(s => s.map((x,i) => i===4 ? {...x, status:"running"} : x));
    await delay(1200);
    setSteps(s => s.map((x,i) => i===4 ? {...x, status:"done",
      data: classified.ai_suggested_solution
        ? classified.ai_suggested_solution.split("\n")[0]
        : "Solution generated by GPT-4o"} : x));
    await delay(400);
    // Step 5: Close
    setSteps(s => s.map((x,i) => i===5 ? {...x, status:"running"} : x));
    await delay(400);
    setSteps(s => s.map((x,i) => i===5 ? {...x, status:"done", data:"Ticket closed"} : x));
    setResult(classified);
    setRunning(false);
  }
  function delay(ms: number) { return new Promise(r => setTimeout(r, ms)); }
  const statusIcon: Record<string,string> = { idle:"○", running:"⟳", done:"✓", error:"✗" };
  const statusColor: Record<string,string> = {
    idle:"text-gray-500", running:"text-yellow-400 animate-spin", done:"text-green-400", error:"text-red-400"
  };
  return (
    <div className="min-h-screen bg-gray-950 text-white p-6">
      <div className="max-w-3xl mx-auto">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-2xl font-bold">🤖 Live AI Agent Demo</h1>
            <p className="text-gray-400">Watch the 6-node LangGraph pipeline process your ticket</p>
          </div>
          <a href="/" className="text-indigo-400 hover:text-indigo-300">← Dashboard</a>
        </div>
        {/* Input */}
        <div className="bg-gray-800 rounded-xl p-5 border border-gray-700 mb-6">
          <div className="mb-3">
            <label className="text-xs text-gray-400 uppercase mb-1 block">Ticket Title</label>
            <input value={title} onChange={e => setTitle(e.target.value)}
              className="w-full bg-gray-900 border border-gray-600 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500" />
          </div>
          <div className="mb-4">
            <label className="text-xs text-gray-400 uppercase mb-1 block">Description</label>
            <textarea value={desc} onChange={e => setDesc(e.target.value)} rows={3}
              className="w-full bg-gray-900 border border-gray-600 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500 resize-none" />
          </div>
          <button onClick={runDemo} disabled={running}
            className="w-full bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed rounded-lg py-3 font-semibold transition text-white">
            {running ? "⟳ Agent Running..." : "🚀 Run AI Agent Pipeline"}
          </button>
        </div>
        {/* Pipeline Nodes */}
        <div className="space-y-3 mb-6">
          {steps.map((step, i) => (
            <div key={i} className={`flex items-center gap-4 bg-gray-800 rounded-xl px-5 py-4 border transition-all duration-300
              ${step.status==="done" ? "border-green-700" : step.status==="running" ? "border-yellow-500" : "border-gray-700"}`}>
              <span className={`text-xl ${statusColor[step.status]}`}>{statusIcon[step.status]}</span>
              <div className="flex-1">
                <div className="font-medium">{step.node}</div>
                {step.data && <div className="text-sm text-gray-400 mt-0.5">{step.data}</div>}
              </div>
              {step.ms && <div className="text-xs text-gray-500">{step.ms}ms</div>}
            </div>
          ))}
        </div>
        {/* Result */}
        {result && (
          <div className="bg-gray-800 rounded-xl p-5 border border-indigo-700">
            <h2 className="font-bold text-indigo-400 mb-3">✅ Pipeline Complete — {result.ticket_number}</h2>
            <div className="grid grid-cols-2 gap-3 text-sm">
              {[
                ["Category",    result.category],
                ["Priority",    result.priority],
                ["Status",      result.status],
                ["Urgency",     result.urgency_score ? `${(result.urgency_score*100).toFixed(0)}%` : "—"],
              ].map(([k,v]) => (
                <div key={k} className="bg-gray-900 rounded-lg p-3">
                  <div className="text-gray-500 text-xs uppercase">{k}</div>
                  <div className="text-white font-medium mt-1 capitalize">{v}</div>
                </div>
              ))}
            </div>
            {result.ai_summary && (
              <div className="mt-3 bg-gray-900 rounded-lg p-3">
                <div className="text-gray-500 text-xs uppercase mb-1">AI Summary</div>
                <div className="text-gray-200 text-sm">{result.ai_summary}</div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}






