"""add omnichannel source fields to tickets

Revision ID: 41d80afa0572
Revises: 3942b7d0c201
Create Date: 2026-05-10 07:36:29.301666+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '41d80afa0572'
down_revision: Union[str, None] = '3942b7d0c201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('source', sa.String(length=50), server_default='api', nullable=False))
    op.add_column('tickets', sa.Column('source_ref_id', sa.String(length=255), nullable=True))
    op.add_column('tickets', sa.Column('source_metadata', sa.JSON(), server_default='{}', nullable=False))
    op.create_index(op.f('ix_tickets_source'), 'tickets', ['source'], unique=False)
    op.create_index(op.f('ix_tickets_source_ref_id'), 'tickets', ['source_ref_id'], unique=False)
    op.drop_column('tickets', 'search_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tickets_source_ref_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_source'), table_name='tickets')
    op.drop_column('tickets', 'source_metadata')
    op.drop_column('tickets', 'source_ref_id')
    op.drop_column('tickets', 'source')
    # ### end Alembic commands ###
